networks:
  server:
    external: true
volumes:
  phpsocket:
services:
  nginx:
    container_name: ${ENVIRONMENT}-nginx
    build: ./docker/nginx
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx:/etc/nginx
      - ./php/public:/etc/nginx/html/website:ro
      - phpsocket:/var/run
    ports:
      - ${HTTP_PORT}:80
    networks:
      - server
  php:
    container_name: ${ENVIRONMENT}-php
    build:
      context: ./docker/php
      target: php
    volumes:
      - ./php:/var/www/html
      - ./db:/var/data/
      - phpsocket:/var/run
    networks:
      - server
    restart: always
    depends_on:
      composer:
        condition: service_completed_successfully
  composer:
    container_name: ${ENVIRONMENT}-composer
    build:
      context: ./docker/php
      target: composer
    volumes:
      - ./php:/var/www/html
    command: sh -c "composer install"
